// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/star-scope/ent/chain"
	"github.com/loomi-labs/star-scope/ent/contractproposal"
)

// ContractProposalCreate is the builder for creating a ContractProposal entity.
type ContractProposalCreate struct {
	config
	mutation *ContractProposalMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (cpc *ContractProposalCreate) SetCreateTime(t time.Time) *ContractProposalCreate {
	cpc.mutation.SetCreateTime(t)
	return cpc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (cpc *ContractProposalCreate) SetNillableCreateTime(t *time.Time) *ContractProposalCreate {
	if t != nil {
		cpc.SetCreateTime(*t)
	}
	return cpc
}

// SetUpdateTime sets the "update_time" field.
func (cpc *ContractProposalCreate) SetUpdateTime(t time.Time) *ContractProposalCreate {
	cpc.mutation.SetUpdateTime(t)
	return cpc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (cpc *ContractProposalCreate) SetNillableUpdateTime(t *time.Time) *ContractProposalCreate {
	if t != nil {
		cpc.SetUpdateTime(*t)
	}
	return cpc
}

// SetProposalID sets the "proposal_id" field.
func (cpc *ContractProposalCreate) SetProposalID(u uint64) *ContractProposalCreate {
	cpc.mutation.SetProposalID(u)
	return cpc
}

// SetTitle sets the "title" field.
func (cpc *ContractProposalCreate) SetTitle(s string) *ContractProposalCreate {
	cpc.mutation.SetTitle(s)
	return cpc
}

// SetDescription sets the "description" field.
func (cpc *ContractProposalCreate) SetDescription(s string) *ContractProposalCreate {
	cpc.mutation.SetDescription(s)
	return cpc
}

// SetFirstSeenTime sets the "first_seen_time" field.
func (cpc *ContractProposalCreate) SetFirstSeenTime(t time.Time) *ContractProposalCreate {
	cpc.mutation.SetFirstSeenTime(t)
	return cpc
}

// SetVotingEndTime sets the "voting_end_time" field.
func (cpc *ContractProposalCreate) SetVotingEndTime(t time.Time) *ContractProposalCreate {
	cpc.mutation.SetVotingEndTime(t)
	return cpc
}

// SetContractAddress sets the "contract_address" field.
func (cpc *ContractProposalCreate) SetContractAddress(s string) *ContractProposalCreate {
	cpc.mutation.SetContractAddress(s)
	return cpc
}

// SetStatus sets the "status" field.
func (cpc *ContractProposalCreate) SetStatus(c contractproposal.Status) *ContractProposalCreate {
	cpc.mutation.SetStatus(c)
	return cpc
}

// SetChainID sets the "chain" edge to the Chain entity by ID.
func (cpc *ContractProposalCreate) SetChainID(id int) *ContractProposalCreate {
	cpc.mutation.SetChainID(id)
	return cpc
}

// SetNillableChainID sets the "chain" edge to the Chain entity by ID if the given value is not nil.
func (cpc *ContractProposalCreate) SetNillableChainID(id *int) *ContractProposalCreate {
	if id != nil {
		cpc = cpc.SetChainID(*id)
	}
	return cpc
}

// SetChain sets the "chain" edge to the Chain entity.
func (cpc *ContractProposalCreate) SetChain(c *Chain) *ContractProposalCreate {
	return cpc.SetChainID(c.ID)
}

// Mutation returns the ContractProposalMutation object of the builder.
func (cpc *ContractProposalCreate) Mutation() *ContractProposalMutation {
	return cpc.mutation
}

// Save creates the ContractProposal in the database.
func (cpc *ContractProposalCreate) Save(ctx context.Context) (*ContractProposal, error) {
	cpc.defaults()
	return withHooks(ctx, cpc.sqlSave, cpc.mutation, cpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cpc *ContractProposalCreate) SaveX(ctx context.Context) *ContractProposal {
	v, err := cpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cpc *ContractProposalCreate) Exec(ctx context.Context) error {
	_, err := cpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpc *ContractProposalCreate) ExecX(ctx context.Context) {
	if err := cpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cpc *ContractProposalCreate) defaults() {
	if _, ok := cpc.mutation.CreateTime(); !ok {
		v := contractproposal.DefaultCreateTime()
		cpc.mutation.SetCreateTime(v)
	}
	if _, ok := cpc.mutation.UpdateTime(); !ok {
		v := contractproposal.DefaultUpdateTime()
		cpc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cpc *ContractProposalCreate) check() error {
	if _, ok := cpc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ContractProposal.create_time"`)}
	}
	if _, ok := cpc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ContractProposal.update_time"`)}
	}
	if _, ok := cpc.mutation.ProposalID(); !ok {
		return &ValidationError{Name: "proposal_id", err: errors.New(`ent: missing required field "ContractProposal.proposal_id"`)}
	}
	if _, ok := cpc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ContractProposal.title"`)}
	}
	if _, ok := cpc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ContractProposal.description"`)}
	}
	if _, ok := cpc.mutation.FirstSeenTime(); !ok {
		return &ValidationError{Name: "first_seen_time", err: errors.New(`ent: missing required field "ContractProposal.first_seen_time"`)}
	}
	if _, ok := cpc.mutation.VotingEndTime(); !ok {
		return &ValidationError{Name: "voting_end_time", err: errors.New(`ent: missing required field "ContractProposal.voting_end_time"`)}
	}
	if _, ok := cpc.mutation.ContractAddress(); !ok {
		return &ValidationError{Name: "contract_address", err: errors.New(`ent: missing required field "ContractProposal.contract_address"`)}
	}
	if _, ok := cpc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ContractProposal.status"`)}
	}
	if v, ok := cpc.mutation.Status(); ok {
		if err := contractproposal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContractProposal.status": %w`, err)}
		}
	}
	return nil
}

func (cpc *ContractProposalCreate) sqlSave(ctx context.Context) (*ContractProposal, error) {
	if err := cpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cpc.mutation.id = &_node.ID
	cpc.mutation.done = true
	return _node, nil
}

func (cpc *ContractProposalCreate) createSpec() (*ContractProposal, *sqlgraph.CreateSpec) {
	var (
		_node = &ContractProposal{config: cpc.config}
		_spec = sqlgraph.NewCreateSpec(contractproposal.Table, sqlgraph.NewFieldSpec(contractproposal.FieldID, field.TypeInt))
	)
	if value, ok := cpc.mutation.CreateTime(); ok {
		_spec.SetField(contractproposal.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := cpc.mutation.UpdateTime(); ok {
		_spec.SetField(contractproposal.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := cpc.mutation.ProposalID(); ok {
		_spec.SetField(contractproposal.FieldProposalID, field.TypeUint64, value)
		_node.ProposalID = value
	}
	if value, ok := cpc.mutation.Title(); ok {
		_spec.SetField(contractproposal.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := cpc.mutation.Description(); ok {
		_spec.SetField(contractproposal.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := cpc.mutation.FirstSeenTime(); ok {
		_spec.SetField(contractproposal.FieldFirstSeenTime, field.TypeTime, value)
		_node.FirstSeenTime = value
	}
	if value, ok := cpc.mutation.VotingEndTime(); ok {
		_spec.SetField(contractproposal.FieldVotingEndTime, field.TypeTime, value)
		_node.VotingEndTime = value
	}
	if value, ok := cpc.mutation.ContractAddress(); ok {
		_spec.SetField(contractproposal.FieldContractAddress, field.TypeString, value)
		_node.ContractAddress = value
	}
	if value, ok := cpc.mutation.Status(); ok {
		_spec.SetField(contractproposal.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := cpc.mutation.ChainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contractproposal.ChainTable,
			Columns: []string{contractproposal.ChainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chain_contract_proposals = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContractProposalCreateBulk is the builder for creating many ContractProposal entities in bulk.
type ContractProposalCreateBulk struct {
	config
	builders []*ContractProposalCreate
}

// Save creates the ContractProposal entities in the database.
func (cpcb *ContractProposalCreateBulk) Save(ctx context.Context) ([]*ContractProposal, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cpcb.builders))
	nodes := make([]*ContractProposal, len(cpcb.builders))
	mutators := make([]Mutator, len(cpcb.builders))
	for i := range cpcb.builders {
		func(i int, root context.Context) {
			builder := cpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContractProposalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cpcb *ContractProposalCreateBulk) SaveX(ctx context.Context) []*ContractProposal {
	v, err := cpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cpcb *ContractProposalCreateBulk) Exec(ctx context.Context) error {
	_, err := cpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpcb *ContractProposalCreateBulk) ExecX(ctx context.Context) {
	if err := cpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
