// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/star-scope/ent/event"
	"github.com/loomi-labs/star-scope/ent/eventlistener"
	"github.com/loomi-labs/star-scope/ent/predicate"
	"github.com/loomi-labs/star-scope/ent/schema"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdateTime sets the "update_time" field.
func (eu *EventUpdate) SetUpdateTime(t time.Time) *EventUpdate {
	eu.mutation.SetUpdateTime(t)
	return eu
}

// SetEventType sets the "event_type" field.
func (eu *EventUpdate) SetEventType(et event.EventType) *EventUpdate {
	eu.mutation.SetEventType(et)
	return eu
}

// SetChainEvent sets the "chain_event" field.
func (eu *EventUpdate) SetChainEvent(sews *schema.ChainEventWithScan) *EventUpdate {
	eu.mutation.SetChainEvent(sews)
	return eu
}

// ClearChainEvent clears the value of the "chain_event" field.
func (eu *EventUpdate) ClearChainEvent() *EventUpdate {
	eu.mutation.ClearChainEvent()
	return eu
}

// SetContractEvent sets the "contract_event" field.
func (eu *EventUpdate) SetContractEvent(sews *schema.ContractEventWithScan) *EventUpdate {
	eu.mutation.SetContractEvent(sews)
	return eu
}

// ClearContractEvent clears the value of the "contract_event" field.
func (eu *EventUpdate) ClearContractEvent() *EventUpdate {
	eu.mutation.ClearContractEvent()
	return eu
}

// SetWalletEvent sets the "wallet_event" field.
func (eu *EventUpdate) SetWalletEvent(sews *schema.WalletEventWithScan) *EventUpdate {
	eu.mutation.SetWalletEvent(sews)
	return eu
}

// ClearWalletEvent clears the value of the "wallet_event" field.
func (eu *EventUpdate) ClearWalletEvent() *EventUpdate {
	eu.mutation.ClearWalletEvent()
	return eu
}

// SetDataType sets the "data_type" field.
func (eu *EventUpdate) SetDataType(et event.DataType) *EventUpdate {
	eu.mutation.SetDataType(et)
	return eu
}

// SetNotifyTime sets the "notify_time" field.
func (eu *EventUpdate) SetNotifyTime(t time.Time) *EventUpdate {
	eu.mutation.SetNotifyTime(t)
	return eu
}

// SetNillableNotifyTime sets the "notify_time" field if the given value is not nil.
func (eu *EventUpdate) SetNillableNotifyTime(t *time.Time) *EventUpdate {
	if t != nil {
		eu.SetNotifyTime(*t)
	}
	return eu
}

// SetIsRead sets the "is_read" field.
func (eu *EventUpdate) SetIsRead(b bool) *EventUpdate {
	eu.mutation.SetIsRead(b)
	return eu
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (eu *EventUpdate) SetNillableIsRead(b *bool) *EventUpdate {
	if b != nil {
		eu.SetIsRead(*b)
	}
	return eu
}

// SetEventListenerID sets the "event_listener" edge to the EventListener entity by ID.
func (eu *EventUpdate) SetEventListenerID(id int) *EventUpdate {
	eu.mutation.SetEventListenerID(id)
	return eu
}

// SetNillableEventListenerID sets the "event_listener" edge to the EventListener entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableEventListenerID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetEventListenerID(*id)
	}
	return eu
}

// SetEventListener sets the "event_listener" edge to the EventListener entity.
func (eu *EventUpdate) SetEventListener(e *EventListener) *EventUpdate {
	return eu.SetEventListenerID(e.ID)
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// ClearEventListener clears the "event_listener" edge to the EventListener entity.
func (eu *EventUpdate) ClearEventListener() *EventUpdate {
	eu.mutation.ClearEventListener()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EventUpdate) defaults() {
	if _, ok := eu.mutation.UpdateTime(); !ok {
		v := event.UpdateDefaultUpdateTime()
		eu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	if v, ok := eu.mutation.DataType(); ok {
		if err := event.DataTypeValidator(v); err != nil {
			return &ValidationError{Name: "data_type", err: fmt.Errorf(`ent: validator failed for field "Event.data_type": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdateTime(); ok {
		_spec.SetField(event.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := eu.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := eu.mutation.ChainEvent(); ok {
		_spec.SetField(event.FieldChainEvent, field.TypeBytes, value)
	}
	if eu.mutation.ChainEventCleared() {
		_spec.ClearField(event.FieldChainEvent, field.TypeBytes)
	}
	if value, ok := eu.mutation.ContractEvent(); ok {
		_spec.SetField(event.FieldContractEvent, field.TypeBytes, value)
	}
	if eu.mutation.ContractEventCleared() {
		_spec.ClearField(event.FieldContractEvent, field.TypeBytes)
	}
	if value, ok := eu.mutation.WalletEvent(); ok {
		_spec.SetField(event.FieldWalletEvent, field.TypeBytes, value)
	}
	if eu.mutation.WalletEventCleared() {
		_spec.ClearField(event.FieldWalletEvent, field.TypeBytes)
	}
	if value, ok := eu.mutation.DataType(); ok {
		_spec.SetField(event.FieldDataType, field.TypeEnum, value)
	}
	if value, ok := eu.mutation.NotifyTime(); ok {
		_spec.SetField(event.FieldNotifyTime, field.TypeTime, value)
	}
	if value, ok := eu.mutation.IsRead(); ok {
		_spec.SetField(event.FieldIsRead, field.TypeBool, value)
	}
	if eu.mutation.EventListenerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EventListenerTable,
			Columns: []string{event.EventListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventlistener.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.EventListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EventListenerTable,
			Columns: []string{event.EventListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventlistener.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetUpdateTime sets the "update_time" field.
func (euo *EventUpdateOne) SetUpdateTime(t time.Time) *EventUpdateOne {
	euo.mutation.SetUpdateTime(t)
	return euo
}

// SetEventType sets the "event_type" field.
func (euo *EventUpdateOne) SetEventType(et event.EventType) *EventUpdateOne {
	euo.mutation.SetEventType(et)
	return euo
}

// SetChainEvent sets the "chain_event" field.
func (euo *EventUpdateOne) SetChainEvent(sews *schema.ChainEventWithScan) *EventUpdateOne {
	euo.mutation.SetChainEvent(sews)
	return euo
}

// ClearChainEvent clears the value of the "chain_event" field.
func (euo *EventUpdateOne) ClearChainEvent() *EventUpdateOne {
	euo.mutation.ClearChainEvent()
	return euo
}

// SetContractEvent sets the "contract_event" field.
func (euo *EventUpdateOne) SetContractEvent(sews *schema.ContractEventWithScan) *EventUpdateOne {
	euo.mutation.SetContractEvent(sews)
	return euo
}

// ClearContractEvent clears the value of the "contract_event" field.
func (euo *EventUpdateOne) ClearContractEvent() *EventUpdateOne {
	euo.mutation.ClearContractEvent()
	return euo
}

// SetWalletEvent sets the "wallet_event" field.
func (euo *EventUpdateOne) SetWalletEvent(sews *schema.WalletEventWithScan) *EventUpdateOne {
	euo.mutation.SetWalletEvent(sews)
	return euo
}

// ClearWalletEvent clears the value of the "wallet_event" field.
func (euo *EventUpdateOne) ClearWalletEvent() *EventUpdateOne {
	euo.mutation.ClearWalletEvent()
	return euo
}

// SetDataType sets the "data_type" field.
func (euo *EventUpdateOne) SetDataType(et event.DataType) *EventUpdateOne {
	euo.mutation.SetDataType(et)
	return euo
}

// SetNotifyTime sets the "notify_time" field.
func (euo *EventUpdateOne) SetNotifyTime(t time.Time) *EventUpdateOne {
	euo.mutation.SetNotifyTime(t)
	return euo
}

// SetNillableNotifyTime sets the "notify_time" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableNotifyTime(t *time.Time) *EventUpdateOne {
	if t != nil {
		euo.SetNotifyTime(*t)
	}
	return euo
}

// SetIsRead sets the "is_read" field.
func (euo *EventUpdateOne) SetIsRead(b bool) *EventUpdateOne {
	euo.mutation.SetIsRead(b)
	return euo
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableIsRead(b *bool) *EventUpdateOne {
	if b != nil {
		euo.SetIsRead(*b)
	}
	return euo
}

// SetEventListenerID sets the "event_listener" edge to the EventListener entity by ID.
func (euo *EventUpdateOne) SetEventListenerID(id int) *EventUpdateOne {
	euo.mutation.SetEventListenerID(id)
	return euo
}

// SetNillableEventListenerID sets the "event_listener" edge to the EventListener entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEventListenerID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetEventListenerID(*id)
	}
	return euo
}

// SetEventListener sets the "event_listener" edge to the EventListener entity.
func (euo *EventUpdateOne) SetEventListener(e *EventListener) *EventUpdateOne {
	return euo.SetEventListenerID(e.ID)
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// ClearEventListener clears the "event_listener" edge to the EventListener entity.
func (euo *EventUpdateOne) ClearEventListener() *EventUpdateOne {
	euo.mutation.ClearEventListener()
	return euo
}

// Where appends a list predicates to the EventUpdate builder.
func (euo *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EventUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdateTime(); !ok {
		v := event.UpdateDefaultUpdateTime()
		euo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	if v, ok := euo.mutation.DataType(); ok {
		if err := event.DataTypeValidator(v); err != nil {
			return &ValidationError{Name: "data_type", err: fmt.Errorf(`ent: validator failed for field "Event.data_type": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdateTime(); ok {
		_spec.SetField(event.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := euo.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := euo.mutation.ChainEvent(); ok {
		_spec.SetField(event.FieldChainEvent, field.TypeBytes, value)
	}
	if euo.mutation.ChainEventCleared() {
		_spec.ClearField(event.FieldChainEvent, field.TypeBytes)
	}
	if value, ok := euo.mutation.ContractEvent(); ok {
		_spec.SetField(event.FieldContractEvent, field.TypeBytes, value)
	}
	if euo.mutation.ContractEventCleared() {
		_spec.ClearField(event.FieldContractEvent, field.TypeBytes)
	}
	if value, ok := euo.mutation.WalletEvent(); ok {
		_spec.SetField(event.FieldWalletEvent, field.TypeBytes, value)
	}
	if euo.mutation.WalletEventCleared() {
		_spec.ClearField(event.FieldWalletEvent, field.TypeBytes)
	}
	if value, ok := euo.mutation.DataType(); ok {
		_spec.SetField(event.FieldDataType, field.TypeEnum, value)
	}
	if value, ok := euo.mutation.NotifyTime(); ok {
		_spec.SetField(event.FieldNotifyTime, field.TypeTime, value)
	}
	if value, ok := euo.mutation.IsRead(); ok {
		_spec.SetField(event.FieldIsRead, field.TypeBool, value)
	}
	if euo.mutation.EventListenerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EventListenerTable,
			Columns: []string{event.EventListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventlistener.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.EventListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EventListenerTable,
			Columns: []string{event.EventListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventlistener.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
