// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/star-scope/ent/state"
)

// StateCreate is the builder for creating a State entity.
type StateCreate struct {
	config
	mutation *StateMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sc *StateCreate) SetCreateTime(t time.Time) *StateCreate {
	sc.mutation.SetCreateTime(t)
	return sc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sc *StateCreate) SetNillableCreateTime(t *time.Time) *StateCreate {
	if t != nil {
		sc.SetCreateTime(*t)
	}
	return sc
}

// SetUpdateTime sets the "update_time" field.
func (sc *StateCreate) SetUpdateTime(t time.Time) *StateCreate {
	sc.mutation.SetUpdateTime(t)
	return sc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sc *StateCreate) SetNillableUpdateTime(t *time.Time) *StateCreate {
	if t != nil {
		sc.SetUpdateTime(*t)
	}
	return sc
}

// SetEntity sets the "entity" field.
func (sc *StateCreate) SetEntity(s state.Entity) *StateCreate {
	sc.mutation.SetEntity(s)
	return sc
}

// SetLastEventTime sets the "last_event_time" field.
func (sc *StateCreate) SetLastEventTime(t time.Time) *StateCreate {
	sc.mutation.SetLastEventTime(t)
	return sc
}

// SetNillableLastEventTime sets the "last_event_time" field if the given value is not nil.
func (sc *StateCreate) SetNillableLastEventTime(t *time.Time) *StateCreate {
	if t != nil {
		sc.SetLastEventTime(*t)
	}
	return sc
}

// Mutation returns the StateMutation object of the builder.
func (sc *StateCreate) Mutation() *StateMutation {
	return sc.mutation
}

// Save creates the State in the database.
func (sc *StateCreate) Save(ctx context.Context) (*State, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StateCreate) SaveX(ctx context.Context) *State {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StateCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StateCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StateCreate) defaults() {
	if _, ok := sc.mutation.CreateTime(); !ok {
		v := state.DefaultCreateTime()
		sc.mutation.SetCreateTime(v)
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		v := state.DefaultUpdateTime()
		sc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StateCreate) check() error {
	if _, ok := sc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "State.create_time"`)}
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "State.update_time"`)}
	}
	if _, ok := sc.mutation.Entity(); !ok {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required field "State.entity"`)}
	}
	if v, ok := sc.mutation.Entity(); ok {
		if err := state.EntityValidator(v); err != nil {
			return &ValidationError{Name: "entity", err: fmt.Errorf(`ent: validator failed for field "State.entity": %w`, err)}
		}
	}
	return nil
}

func (sc *StateCreate) sqlSave(ctx context.Context) (*State, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StateCreate) createSpec() (*State, *sqlgraph.CreateSpec) {
	var (
		_node = &State{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(state.Table, sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.CreateTime(); ok {
		_spec.SetField(state.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := sc.mutation.UpdateTime(); ok {
		_spec.SetField(state.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := sc.mutation.Entity(); ok {
		_spec.SetField(state.FieldEntity, field.TypeEnum, value)
		_node.Entity = value
	}
	if value, ok := sc.mutation.LastEventTime(); ok {
		_spec.SetField(state.FieldLastEventTime, field.TypeTime, value)
		_node.LastEventTime = value
	}
	return _node, _spec
}

// StateCreateBulk is the builder for creating many State entities in bulk.
type StateCreateBulk struct {
	config
	builders []*StateCreate
}

// Save creates the State entities in the database.
func (scb *StateCreateBulk) Save(ctx context.Context) ([]*State, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*State, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StateCreateBulk) SaveX(ctx context.Context) []*State {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StateCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StateCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
