version: '3.9'

services:
  grpc:
    image: ghcr.io/loomi-labs/star-scope-server:main
    working_dir: /app
    secrets:
      - starscope-env
    command: /bin/sh -c "source /run/secrets/starscope-env && /starscope service grpc"

networks:
  caddy:
    external: true

secrets:
  starscope-env:
    external: true
  pgadmin-password:
    external: true
