-- create "comm_channels" table
CREATE TABLE "comm_channels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 30064771072), "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "telegram_chat_id" bigint NOT NULL, "discord_channel_id" bigint NOT NULL, "is_group" boolean NOT NULL, PRIMARY KEY ("id"));
-- create index "comm_channels_discord_channel_id_key" to table: "comm_channels"
CREATE UNIQUE INDEX "comm_channels_discord_channel_id_key" ON "comm_channels" ("discord_channel_id");
-- create index "comm_channels_telegram_chat_id_key" to table: "comm_channels"
CREATE UNIQUE INDEX "comm_channels_telegram_chat_id_key" ON "comm_channels" ("telegram_chat_id");
-- modify "event_listeners" table
ALTER TABLE "event_listeners" DROP COLUMN "user_event_listeners";
-- create "comm_channel_event_listeners" table
CREATE TABLE "comm_channel_event_listeners" ("comm_channel_id" bigint NOT NULL, "event_listener_id" bigint NOT NULL, PRIMARY KEY ("comm_channel_id", "event_listener_id"), CONSTRAINT "comm_channel_event_listeners_comm_channel_id" FOREIGN KEY ("comm_channel_id") REFERENCES "comm_channels" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "comm_channel_event_listeners_event_listener_id" FOREIGN KEY ("event_listener_id") REFERENCES "event_listeners" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "user_event_listeners" table
CREATE TABLE "user_event_listeners" ("user_id" bigint NOT NULL, "event_listener_id" bigint NOT NULL, PRIMARY KEY ("user_id", "event_listener_id"), CONSTRAINT "user_event_listeners_event_listener_id" FOREIGN KEY ("event_listener_id") REFERENCES "event_listeners" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_event_listeners_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "user_comm_channels" table
CREATE TABLE "user_comm_channels" ("user_id" bigint NOT NULL, "comm_channel_id" bigint NOT NULL, PRIMARY KEY ("user_id", "comm_channel_id"), CONSTRAINT "user_comm_channels_comm_channel_id" FOREIGN KEY ("comm_channel_id") REFERENCES "comm_channels" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_comm_channels_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- add pk ranges for ('comm_channels') tables
INSERT INTO "ent_types" ("type") VALUES ('comm_channels');
