-- create "states" table
CREATE TABLE "states" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 38654705664), "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "entity" character varying NOT NULL, "last_event_time" timestamptz NULL, PRIMARY KEY ("id"));
-- create index "state_entity" to table: "states"
CREATE UNIQUE INDEX "state_entity" ON "states" ("entity");
-- add pk ranges for ('states') tables
INSERT INTO "ent_types" ("type") VALUES ('states');
