-- create "user_setups" table
CREATE TABLE "user_setups" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 34359738368), "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "step" character varying NOT NULL DEFAULT 'one', "is_finished" boolean NOT NULL DEFAULT false, "is_validator" boolean NOT NULL DEFAULT false, "wallet_addresses" jsonb NULL, "notify_funding" boolean NOT NULL DEFAULT false, "notify_staking" boolean NOT NULL DEFAULT false, "notify_gov_new_proposal" boolean NOT NULL DEFAULT false, "notify_gov_voting_end" boolean NOT NULL DEFAULT false, "notify_gov_voting_reminder" boolean NOT NULL DEFAULT false, "user_setup" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "user_setups_users_setup" FOREIGN KEY ("user_setup") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create index "user_setups_user_setup_key" to table: "user_setups"
CREATE UNIQUE INDEX "user_setups_user_setup_key" ON "user_setups" ("user_setup");
-- modify "validators" table
ALTER TABLE "validators" ADD COLUMN "identity" character varying NOT NULL DEFAULT '', ADD COLUMN "logo_url" character varying NULL, ADD COLUMN "user_setup_validators" bigint NULL, ADD CONSTRAINT "validators_user_setups_validators" FOREIGN KEY ("user_setup_validators") REFERENCES "user_setups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- add pk ranges for ('user_setups') tables
INSERT INTO "ent_types" ("type") VALUES ('user_setups');
