-- create "chains" table
CREATE TABLE "chains" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "chain_id" character varying NOT NULL, "name" character varying NOT NULL, "pretty_name" character varying NOT NULL, "path" character varying NOT NULL, "image" character varying NOT NULL, "bech32_prefix" character varying NOT NULL, "indexing_height" bigint NOT NULL DEFAULT 0, "has_custom_indexer" boolean NOT NULL DEFAULT false, "handled_message_types" character varying NOT NULL DEFAULT '', "unhandled_message_types" character varying NOT NULL DEFAULT '', "is_enabled" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- create index "chain_name" to table: "chains"
CREATE UNIQUE INDEX "chain_name" ON "chains" ("name");
-- create index "chains_chain_id_key" to table: "chains"
CREATE UNIQUE INDEX "chains_chain_id_key" ON "chains" ("chain_id");
-- create index "chains_name_key" to table: "chains"
CREATE UNIQUE INDEX "chains_name_key" ON "chains" ("name");
-- create index "chains_pretty_name_key" to table: "chains"
CREATE UNIQUE INDEX "chains_pretty_name_key" ON "chains" ("pretty_name");
-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "wallet_address" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'user', PRIMARY KEY ("id"));
-- create "event_listeners" table
CREATE TABLE "event_listeners" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "wallet_address" character varying NOT NULL, "chain_event_listeners" bigint NULL, "user_event_listeners" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "event_listeners_chains_event_listeners" FOREIGN KEY ("chain_event_listeners") REFERENCES "chains" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "event_listeners_users_event_listeners" FOREIGN KEY ("user_event_listeners") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "events" table
CREATE TABLE "events" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "type" character varying NOT NULL, "tx_event" bytea NOT NULL, "notify_time" timestamptz NOT NULL, "event_listener_events" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "events_event_listeners_events" FOREIGN KEY ("event_listener_events") REFERENCES "event_listeners" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
