-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "wallet_address" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'user', PRIMARY KEY ("id"));
-- create "projects" table
CREATE TABLE "projects" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "user_projects" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "projects_users_projects" FOREIGN KEY ("user_projects") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "channels" table
CREATE TABLE "channels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "project_channels" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "channels_projects_channels" FOREIGN KEY ("project_channels") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "chains" table
CREATE TABLE "chains" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "image" character varying NOT NULL, "indexing_height" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- create index "chain_name" to table: "chains"
CREATE UNIQUE INDEX "chain_name" ON "chains" ("name");
-- create index "chains_name_key" to table: "chains"
CREATE UNIQUE INDEX "chains_name_key" ON "chains" ("name");
-- create "event_listeners" table
CREATE TABLE "event_listeners" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "wallet_address" character varying NOT NULL, "chain_event_listeners" bigint NULL, "channel_event_listeners" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "event_listeners_chains_event_listeners" FOREIGN KEY ("chain_event_listeners") REFERENCES "chains" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "event_listeners_channels_event_listeners" FOREIGN KEY ("channel_event_listeners") REFERENCES "channels" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "events" table
CREATE TABLE "events" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "type" character varying NOT NULL, "tx_event" bytea NOT NULL, "notify_time" timestamptz NOT NULL, "event_listener_events" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "events_event_listeners_events" FOREIGN KEY ("event_listener_events") REFERENCES "event_listeners" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
