// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: grpc/auth/authpb/auth_service.proto

package authpbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	authpb "github.com/loomi-labs/star-scope/grpc/auth/authpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "starscope.grpc.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceKeplrLoginProcedure is the fully-qualified name of the AuthService's KeplrLogin RPC.
	AuthServiceKeplrLoginProcedure = "/starscope.grpc.AuthService/KeplrLogin"
	// AuthServiceTelegramLoginProcedure is the fully-qualified name of the AuthService's TelegramLogin
	// RPC.
	AuthServiceTelegramLoginProcedure = "/starscope.grpc.AuthService/TelegramLogin"
	// AuthServiceDiscordLoginProcedure is the fully-qualified name of the AuthService's DiscordLogin
	// RPC.
	AuthServiceDiscordLoginProcedure = "/starscope.grpc.AuthService/DiscordLogin"
	// AuthServiceRefreshAccessTokenProcedure is the fully-qualified name of the AuthService's
	// RefreshAccessToken RPC.
	AuthServiceRefreshAccessTokenProcedure = "/starscope.grpc.AuthService/RefreshAccessToken"
	// AuthServiceConnectDiscordProcedure is the fully-qualified name of the AuthService's
	// ConnectDiscord RPC.
	AuthServiceConnectDiscordProcedure = "/starscope.grpc.AuthService/ConnectDiscord"
	// AuthServiceConnectTelegramProcedure is the fully-qualified name of the AuthService's
	// ConnectTelegram RPC.
	AuthServiceConnectTelegramProcedure = "/starscope.grpc.AuthService/ConnectTelegram"
)

// AuthServiceClient is a client for the starscope.grpc.AuthService service.
type AuthServiceClient interface {
	KeplrLogin(context.Context, *connect_go.Request[authpb.KeplrLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	TelegramLogin(context.Context, *connect_go.Request[authpb.TelegramLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	DiscordLogin(context.Context, *connect_go.Request[authpb.DiscordLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	RefreshAccessToken(context.Context, *connect_go.Request[authpb.RefreshAccessTokenRequest]) (*connect_go.Response[authpb.RefreshAccessTokenResponse], error)
	ConnectDiscord(context.Context, *connect_go.Request[authpb.ConnectDiscordRequest]) (*connect_go.Response[emptypb.Empty], error)
	ConnectTelegram(context.Context, *connect_go.Request[authpb.ConnectTelegramRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewAuthServiceClient constructs a client for the starscope.grpc.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		keplrLogin: connect_go.NewClient[authpb.KeplrLoginRequest, authpb.LoginResponse](
			httpClient,
			baseURL+AuthServiceKeplrLoginProcedure,
			opts...,
		),
		telegramLogin: connect_go.NewClient[authpb.TelegramLoginRequest, authpb.LoginResponse](
			httpClient,
			baseURL+AuthServiceTelegramLoginProcedure,
			opts...,
		),
		discordLogin: connect_go.NewClient[authpb.DiscordLoginRequest, authpb.LoginResponse](
			httpClient,
			baseURL+AuthServiceDiscordLoginProcedure,
			opts...,
		),
		refreshAccessToken: connect_go.NewClient[authpb.RefreshAccessTokenRequest, authpb.RefreshAccessTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshAccessTokenProcedure,
			opts...,
		),
		connectDiscord: connect_go.NewClient[authpb.ConnectDiscordRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceConnectDiscordProcedure,
			opts...,
		),
		connectTelegram: connect_go.NewClient[authpb.ConnectTelegramRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceConnectTelegramProcedure,
			opts...,
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	keplrLogin         *connect_go.Client[authpb.KeplrLoginRequest, authpb.LoginResponse]
	telegramLogin      *connect_go.Client[authpb.TelegramLoginRequest, authpb.LoginResponse]
	discordLogin       *connect_go.Client[authpb.DiscordLoginRequest, authpb.LoginResponse]
	refreshAccessToken *connect_go.Client[authpb.RefreshAccessTokenRequest, authpb.RefreshAccessTokenResponse]
	connectDiscord     *connect_go.Client[authpb.ConnectDiscordRequest, emptypb.Empty]
	connectTelegram    *connect_go.Client[authpb.ConnectTelegramRequest, emptypb.Empty]
}

// KeplrLogin calls starscope.grpc.AuthService.KeplrLogin.
func (c *authServiceClient) KeplrLogin(ctx context.Context, req *connect_go.Request[authpb.KeplrLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return c.keplrLogin.CallUnary(ctx, req)
}

// TelegramLogin calls starscope.grpc.AuthService.TelegramLogin.
func (c *authServiceClient) TelegramLogin(ctx context.Context, req *connect_go.Request[authpb.TelegramLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return c.telegramLogin.CallUnary(ctx, req)
}

// DiscordLogin calls starscope.grpc.AuthService.DiscordLogin.
func (c *authServiceClient) DiscordLogin(ctx context.Context, req *connect_go.Request[authpb.DiscordLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return c.discordLogin.CallUnary(ctx, req)
}

// RefreshAccessToken calls starscope.grpc.AuthService.RefreshAccessToken.
func (c *authServiceClient) RefreshAccessToken(ctx context.Context, req *connect_go.Request[authpb.RefreshAccessTokenRequest]) (*connect_go.Response[authpb.RefreshAccessTokenResponse], error) {
	return c.refreshAccessToken.CallUnary(ctx, req)
}

// ConnectDiscord calls starscope.grpc.AuthService.ConnectDiscord.
func (c *authServiceClient) ConnectDiscord(ctx context.Context, req *connect_go.Request[authpb.ConnectDiscordRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.connectDiscord.CallUnary(ctx, req)
}

// ConnectTelegram calls starscope.grpc.AuthService.ConnectTelegram.
func (c *authServiceClient) ConnectTelegram(ctx context.Context, req *connect_go.Request[authpb.ConnectTelegramRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.connectTelegram.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the starscope.grpc.AuthService service.
type AuthServiceHandler interface {
	KeplrLogin(context.Context, *connect_go.Request[authpb.KeplrLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	TelegramLogin(context.Context, *connect_go.Request[authpb.TelegramLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	DiscordLogin(context.Context, *connect_go.Request[authpb.DiscordLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error)
	RefreshAccessToken(context.Context, *connect_go.Request[authpb.RefreshAccessTokenRequest]) (*connect_go.Response[authpb.RefreshAccessTokenResponse], error)
	ConnectDiscord(context.Context, *connect_go.Request[authpb.ConnectDiscordRequest]) (*connect_go.Response[emptypb.Empty], error)
	ConnectTelegram(context.Context, *connect_go.Request[authpb.ConnectTelegramRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(AuthServiceKeplrLoginProcedure, connect_go.NewUnaryHandler(
		AuthServiceKeplrLoginProcedure,
		svc.KeplrLogin,
		opts...,
	))
	mux.Handle(AuthServiceTelegramLoginProcedure, connect_go.NewUnaryHandler(
		AuthServiceTelegramLoginProcedure,
		svc.TelegramLogin,
		opts...,
	))
	mux.Handle(AuthServiceDiscordLoginProcedure, connect_go.NewUnaryHandler(
		AuthServiceDiscordLoginProcedure,
		svc.DiscordLogin,
		opts...,
	))
	mux.Handle(AuthServiceRefreshAccessTokenProcedure, connect_go.NewUnaryHandler(
		AuthServiceRefreshAccessTokenProcedure,
		svc.RefreshAccessToken,
		opts...,
	))
	mux.Handle(AuthServiceConnectDiscordProcedure, connect_go.NewUnaryHandler(
		AuthServiceConnectDiscordProcedure,
		svc.ConnectDiscord,
		opts...,
	))
	mux.Handle(AuthServiceConnectTelegramProcedure, connect_go.NewUnaryHandler(
		AuthServiceConnectTelegramProcedure,
		svc.ConnectTelegram,
		opts...,
	))
	return "/starscope.grpc.AuthService/", mux
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) KeplrLogin(context.Context, *connect_go.Request[authpb.KeplrLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.KeplrLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) TelegramLogin(context.Context, *connect_go.Request[authpb.TelegramLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.TelegramLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) DiscordLogin(context.Context, *connect_go.Request[authpb.DiscordLoginRequest]) (*connect_go.Response[authpb.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.DiscordLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshAccessToken(context.Context, *connect_go.Request[authpb.RefreshAccessTokenRequest]) (*connect_go.Response[authpb.RefreshAccessTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.RefreshAccessToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) ConnectDiscord(context.Context, *connect_go.Request[authpb.ConnectDiscordRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.ConnectDiscord is not implemented"))
}

func (UnimplementedAuthServiceHandler) ConnectTelegram(context.Context, *connect_go.Request[authpb.ConnectTelegramRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("starscope.grpc.AuthService.ConnectTelegram is not implemented"))
}
