// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChainsColumns holds the columns for the "chains" table.
	ChainsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "chain_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "pretty_name", Type: field.TypeString, Unique: true},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString},
		{Name: "bech32_prefix", Type: field.TypeString},
		{Name: "rest_endpoint", Type: field.TypeString, Default: ""},
		{Name: "indexing_height", Type: field.TypeUint64, Default: 0},
		{Name: "has_custom_indexer", Type: field.TypeBool, Default: false},
		{Name: "handled_message_types", Type: field.TypeString, Default: ""},
		{Name: "unhandled_message_types", Type: field.TypeString, Default: ""},
		{Name: "is_enabled", Type: field.TypeBool, Default: false},
	}
	// ChainsTable holds the schema information for the "chains" table.
	ChainsTable = &schema.Table{
		Name:       "chains",
		Columns:    ChainsColumns,
		PrimaryKey: []*schema.Column{ChainsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "chain_name",
				Unique:  true,
				Columns: []*schema.Column{ChainsColumns[4]},
			},
		},
	}
	// CommChannelsColumns holds the columns for the "comm_channels" table.
	CommChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"webpush", "telegram", "discord"}},
		{Name: "telegram_chat_id", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "discord_channel_id", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "is_group", Type: field.TypeBool, Default: false},
	}
	// CommChannelsTable holds the schema information for the "comm_channels" table.
	CommChannelsTable = &schema.Table{
		Name:       "comm_channels",
		Columns:    CommChannelsColumns,
		PrimaryKey: []*schema.Column{CommChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "commchannel_telegram_chat_id",
				Unique:  false,
				Columns: []*schema.Column{CommChannelsColumns[5]},
			},
			{
				Name:    "commchannel_discord_channel_id",
				Unique:  false,
				Columns: []*schema.Column{CommChannelsColumns[6]},
			},
		},
	}
	// ContractProposalsColumns holds the columns for the "contract_proposals" table.
	ContractProposalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "proposal_id", Type: field.TypeUint64},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "first_seen_time", Type: field.TypeTime},
		{Name: "voting_end_time", Type: field.TypeTime},
		{Name: "contract_address", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"OPEN", "REJECTED", "PASSED", "EXECUTED", "CLOSED", "EXECUTION_FAILED"}},
		{Name: "chain_contract_proposals", Type: field.TypeInt, Nullable: true},
	}
	// ContractProposalsTable holds the schema information for the "contract_proposals" table.
	ContractProposalsTable = &schema.Table{
		Name:       "contract_proposals",
		Columns:    ContractProposalsColumns,
		PrimaryKey: []*schema.Column{ContractProposalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contract_proposals_chains_contract_proposals",
				Columns:    []*schema.Column{ContractProposalsColumns[10]},
				RefColumns: []*schema.Column{ChainsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "event_type", Type: field.TypeEnum, Enums: []string{"FUNDING", "STAKING", "DEX", "GOVERNANCE"}},
		{Name: "chain_event", Type: field.TypeBytes, Nullable: true},
		{Name: "contract_event", Type: field.TypeBytes, Nullable: true},
		{Name: "wallet_event", Type: field.TypeBytes, Nullable: true},
		{Name: "data_type", Type: field.TypeEnum, Enums: []string{"WalletEvent_CoinReceived", "WalletEvent_OsmosisPoolUnlock", "WalletEvent_Unstake", "WalletEvent_NeutronTokenVesting", "WalletEvent_Voted", "WalletEvent_VoteReminder", "ChainEvent_ValidatorOutOfActiveSet", "ChainEvent_ValidatorSlash", "ChainEvent_GovernanceProposal_Ongoing", "ChainEvent_GovernanceProposal_Finished", "ContractEvent_ContractGovernanceProposal_Ongoing", "ContractEvent_ContractGovernanceProposal_Finished"}},
		{Name: "notify_time", Type: field.TypeTime},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "is_background", Type: field.TypeBool, Default: false},
		{Name: "event_listener_events", Type: field.TypeInt, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_event_listeners_events",
				Columns:    []*schema.Column{EventsColumns[11]},
				RefColumns: []*schema.Column{EventListenersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// EventListenersColumns holds the columns for the "event_listeners" table.
	EventListenersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "wallet_address", Type: field.TypeString, Nullable: true},
		{Name: "data_type", Type: field.TypeEnum, Enums: []string{"WalletEvent_CoinReceived", "WalletEvent_OsmosisPoolUnlock", "WalletEvent_Unstake", "WalletEvent_NeutronTokenVesting", "WalletEvent_Voted", "WalletEvent_VoteReminder", "ChainEvent_ValidatorOutOfActiveSet", "ChainEvent_ValidatorSlash", "ChainEvent_GovernanceProposal_Ongoing", "ChainEvent_GovernanceProposal_Finished", "ContractEvent_ContractGovernanceProposal_Ongoing", "ContractEvent_ContractGovernanceProposal_Finished"}},
		{Name: "chain_event_listeners", Type: field.TypeInt, Nullable: true},
	}
	// EventListenersTable holds the schema information for the "event_listeners" table.
	EventListenersTable = &schema.Table{
		Name:       "event_listeners",
		Columns:    EventListenersColumns,
		PrimaryKey: []*schema.Column{EventListenersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "event_listeners_chains_event_listeners",
				Columns:    []*schema.Column{EventListenersColumns[5]},
				RefColumns: []*schema.Column{ChainsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProposalsColumns holds the columns for the "proposals" table.
	ProposalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "proposal_id", Type: field.TypeUint64},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "voting_start_time", Type: field.TypeTime},
		{Name: "voting_end_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PROPOSAL_STATUS_UNSPECIFIED", "PROPOSAL_STATUS_DEPOSIT_PERIOD", "PROPOSAL_STATUS_VOTING_PERIOD", "PROPOSAL_STATUS_PASSED", "PROPOSAL_STATUS_REJECTED", "PROPOSAL_STATUS_FAILED"}},
		{Name: "chain_proposals", Type: field.TypeInt, Nullable: true},
	}
	// ProposalsTable holds the schema information for the "proposals" table.
	ProposalsTable = &schema.Table{
		Name:       "proposals",
		Columns:    ProposalsColumns,
		PrimaryKey: []*schema.Column{ProposalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "proposals_chains_proposals",
				Columns:    []*schema.Column{ProposalsColumns[9]},
				RefColumns: []*schema.Column{ChainsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "admin"}, Default: "user"},
		{Name: "telegram_user_id", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "telegram_username", Type: field.TypeString, Nullable: true},
		{Name: "discord_user_id", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "discord_username", Type: field.TypeString, Nullable: true},
		{Name: "wallet_address", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "last_login_time", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_telegram_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
			{
				Name:    "user_discord_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
			{
				Name:    "user_wallet_address",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[8]},
			},
		},
	}
	// ValidatorsColumns holds the columns for the "validators" table.
	ValidatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "operator_address", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "moniker", Type: field.TypeString},
		{Name: "first_inactive_time", Type: field.TypeTime, Nullable: true},
		{Name: "last_slash_validator_period", Type: field.TypeUint64, Nullable: true},
		{Name: "chain_validators", Type: field.TypeInt},
	}
	// ValidatorsTable holds the schema information for the "validators" table.
	ValidatorsTable = &schema.Table{
		Name:       "validators",
		Columns:    ValidatorsColumns,
		PrimaryKey: []*schema.Column{ValidatorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "validators_chains_validators",
				Columns:    []*schema.Column{ValidatorsColumns[8]},
				RefColumns: []*schema.Column{ChainsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "validator_operator_address",
				Unique:  false,
				Columns: []*schema.Column{ValidatorsColumns[3]},
			},
			{
				Name:    "validator_address",
				Unique:  false,
				Columns: []*schema.Column{ValidatorsColumns[4]},
			},
			{
				Name:    "validator_moniker",
				Unique:  false,
				Columns: []*schema.Column{ValidatorsColumns[5]},
			},
			{
				Name:    "validator_moniker_operator_address_chain_validators",
				Unique:  true,
				Columns: []*schema.Column{ValidatorsColumns[5], ValidatorsColumns[3], ValidatorsColumns[8]},
			},
			{
				Name:    "validator_moniker_address_chain_validators",
				Unique:  true,
				Columns: []*schema.Column{ValidatorsColumns[5], ValidatorsColumns[4], ValidatorsColumns[8]},
			},
			{
				Name:    "validator_address_chain_validators",
				Unique:  true,
				Columns: []*schema.Column{ValidatorsColumns[4], ValidatorsColumns[8]},
			},
			{
				Name:    "validator_operator_address_chain_validators",
				Unique:  true,
				Columns: []*schema.Column{ValidatorsColumns[3], ValidatorsColumns[8]},
			},
		},
	}
	// CommChannelEventListenersColumns holds the columns for the "comm_channel_event_listeners" table.
	CommChannelEventListenersColumns = []*schema.Column{
		{Name: "comm_channel_id", Type: field.TypeInt},
		{Name: "event_listener_id", Type: field.TypeInt},
	}
	// CommChannelEventListenersTable holds the schema information for the "comm_channel_event_listeners" table.
	CommChannelEventListenersTable = &schema.Table{
		Name:       "comm_channel_event_listeners",
		Columns:    CommChannelEventListenersColumns,
		PrimaryKey: []*schema.Column{CommChannelEventListenersColumns[0], CommChannelEventListenersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comm_channel_event_listeners_comm_channel_id",
				Columns:    []*schema.Column{CommChannelEventListenersColumns[0]},
				RefColumns: []*schema.Column{CommChannelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "comm_channel_event_listeners_event_listener_id",
				Columns:    []*schema.Column{CommChannelEventListenersColumns[1]},
				RefColumns: []*schema.Column{EventListenersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserEventListenersColumns holds the columns for the "user_event_listeners" table.
	UserEventListenersColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "event_listener_id", Type: field.TypeInt},
	}
	// UserEventListenersTable holds the schema information for the "user_event_listeners" table.
	UserEventListenersTable = &schema.Table{
		Name:       "user_event_listeners",
		Columns:    UserEventListenersColumns,
		PrimaryKey: []*schema.Column{UserEventListenersColumns[0], UserEventListenersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_event_listeners_user_id",
				Columns:    []*schema.Column{UserEventListenersColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_event_listeners_event_listener_id",
				Columns:    []*schema.Column{UserEventListenersColumns[1]},
				RefColumns: []*schema.Column{EventListenersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserCommChannelsColumns holds the columns for the "user_comm_channels" table.
	UserCommChannelsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "comm_channel_id", Type: field.TypeInt},
	}
	// UserCommChannelsTable holds the schema information for the "user_comm_channels" table.
	UserCommChannelsTable = &schema.Table{
		Name:       "user_comm_channels",
		Columns:    UserCommChannelsColumns,
		PrimaryKey: []*schema.Column{UserCommChannelsColumns[0], UserCommChannelsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_comm_channels_user_id",
				Columns:    []*schema.Column{UserCommChannelsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_comm_channels_comm_channel_id",
				Columns:    []*schema.Column{UserCommChannelsColumns[1]},
				RefColumns: []*schema.Column{CommChannelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChainsTable,
		CommChannelsTable,
		ContractProposalsTable,
		EventsTable,
		EventListenersTable,
		ProposalsTable,
		UsersTable,
		ValidatorsTable,
		CommChannelEventListenersTable,
		UserEventListenersTable,
		UserCommChannelsTable,
	}
)

func init() {
	ContractProposalsTable.ForeignKeys[0].RefTable = ChainsTable
	EventsTable.ForeignKeys[0].RefTable = EventListenersTable
	EventListenersTable.ForeignKeys[0].RefTable = ChainsTable
	ProposalsTable.ForeignKeys[0].RefTable = ChainsTable
	ValidatorsTable.ForeignKeys[0].RefTable = ChainsTable
	CommChannelEventListenersTable.ForeignKeys[0].RefTable = CommChannelsTable
	CommChannelEventListenersTable.ForeignKeys[1].RefTable = EventListenersTable
	UserEventListenersTable.ForeignKeys[0].RefTable = UsersTable
	UserEventListenersTable.ForeignKeys[1].RefTable = EventListenersTable
	UserCommChannelsTable.ForeignKeys[0].RefTable = UsersTable
	UserCommChannelsTable.ForeignKeys[1].RefTable = CommChannelsTable
}
