name: Create and publish Docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            server:
              - 'server/**'

      - name: Extract metadata (tags, labels) for server image
        id: meta-server
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.server == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server

      - name: Build and push server Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.server == 'true'
        with:
          context: server/
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}

  build-and-push-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            client:
              - 'client/**'

      - name: Extract metadata (tags, labels) for client image
        id: meta-client
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.client == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-client

      - name: Build and push client Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.client == 'true'
        with:
          context: .
          file: client/Dockerfile
          push: true
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          build-args: |
            DEBUG=true
            GRPC_WEB_ENDPOINT_URL=https://starscope.network
            COSMOS_LOGIN_BUTTON_URL=https://starscope.network/cosmos-login
            WEB_APP_URL=https://starscope.network
            TELEGRAM_BOT_NAME=StarScopeTestBot
            DISCORD_CLIENT_ID=1120308547142549565

  build-and-push-client-cosmos-login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            client-cosmos-login:
              - 'client-cosmos-login/**'

      - name: Extract metadata (tags, labels) for client-cosmos-login image
        id: meta-client-cosmos-login
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.client-cosmos-login == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-client-cosmos-login

      - name: Build and push client-cosmos-login Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.client-cosmos-login == 'true'
        with:
          file: client-cosmos-login/Dockerfile
          push: true
          tags: ${{ steps.meta-client-cosmos-login.outputs.tags }}
          labels: ${{ steps.meta-client-cosmos-login.outputs.labels }}

  build-and-push-base-indexer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            base-indexer:
              - 'indexers/base/**/*'

      - name: Extract metadata (tags, labels) for base-indexer image
        id: meta-base-indexer
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.base-indexer == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-base-indexer

      - name: Build and push indexer Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.base-indexer == 'true'
        with:
          context: indexers/base/
          push: true
          tags: ${{ steps.meta-base-indexer.outputs.tags }}
          labels: ${{ steps.meta-base-indexer.outputs.labels }}

  build-and-push-osmosis-indexer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            osmosis-indexer:
              - 'indexers/osmosis/**/*'

      - name: Extract metadata (tags, labels) for osmosis-indexer image
        id: meta-osmosis-indexer
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.osmosis-indexer == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-osmosis-indexer

      - name: Build and push indexer Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.osmosis-indexer == 'true'
        with:
          context: indexers/osmosis/
          push: true
          tags: ${{ steps.meta-osmosis-indexer.outputs.tags }}
          labels: ${{ steps.meta-osmosis-indexer.outputs.labels }}

  build-and-push-envoy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            envoy:
              - 'data/docker/envoy/**/*'

      - name: Extract metadata (tags, labels) for envoy image
        id: meta-envoy
        uses: docker/metadata-action@v4.3.0
        if: steps.changes.outputs.envoy == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-envoy

      - name: Build and push envoy Docker image
        uses: docker/build-push-action@v4.0.0
        if: steps.changes.outputs.envoy == 'true'
        with:
          context: data/docker/envoy/
          push: true
          tags: ${{ steps.meta-envoy.outputs.tags }}
          labels: ${{ steps.meta-envoy.outputs.labels }}

  deploy-to-swarm:
    needs: [build-and-push-server, build-and-push-client, build-and-push-client-cosmos-login, build-and-push-base-indexer, build-and-push-osmosis-indexer, build-and-push-envoy]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ubuntu@188.166.38.235
          ssh_private_key: ${{ secrets.SWARMY_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SWARMY_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: /home/ubuntu
          stack_file_name: swarm-prod-star-scope.yml
          keep_files: 5
          args: star-scope --with-registry-auth
